### ISSUE TITLE
Support for ARMeshManager

### ISSUE THREAD

**Issue by marwie** [needle-tools/ar-simulation#37]
Currently we dont have support for meshing using the [ARMeshManager ](https://docs.unity3d.com/Packages/com.unity.xr.arfoundation@4.1/manual/mesh-manager.html) so we can't simulate Apples LiDAR scanning yet.

#### Technical Details

- Meshing is implemented via native plugins only
- Registering and discovering a native meshing plugin can be archieved via UnitySubsystemsManifest.json
- For editor subsystem discovery in a package Unity requires the keyword ``xreditorsubsystem`` to be present in the ``package.json:keywords`` array

**Comment by marwie** [comment]
A first mesh has been sent through our meshing subsystem!

![image](https://user-images.githubusercontent.com/5083203/93467012-6c87d400-f8ed-11ea-88b2-e14b3c60e7d1.png)

**Comment by marwie** [comment]
**The basics are working now** (here is a first test with a simple mesh provider component).
We only feed the mesh data via our native XRMeshSubsystem, rendering and update events are all ARMeshManager. 
Now we can write managed components for the actual meshing simulation!

![2020-09-17-160257](https://user-images.githubusercontent.com/5083203/93482081-96e28d00-f8ff-11ea-99cb-fae7152bbd3d.gif)

**Comment by marwie** [comment]
Here is another slightly better gif

![2020-09-17-162631](https://user-images.githubusercontent.com/5083203/93485102-fdb57580-f902-11ea-8e40-8eebaf3dc192.gif)

**Comment by marwie** [comment]
Early version of dynamic sampling

![2020-09-17-183748](https://user-images.githubusercontent.com/5083203/93501004-247ca780-f915-11ea-8ba2-5f50d6a8e619.gif)

**Comment by marwie** [comment]
![2020-09-17-185959](https://user-images.githubusercontent.com/5083203/93503601-986c7f00-f918-11ea-9d67-ee47ca9a2f14.gif)

**Comment by marwie** [comment]
**TODOs**:

- [ ] test building plugin for mac and linux using bee.exe
- [ ] setup pipeline for cross compile
- [ ] integrate plugin in main package and merge to master
- [ ] improve mesh generation: try remove single triangles
- [ ] improve mesh generation: improve meshes locally over time (configureable: start with more noise, become cleaner)

**Comment by marwie** [comment]
## Release initial version as 1.0.4.-preview 

![2020-09-18-162314](https://user-images.githubusercontent.com/5083203/93610020-cca17780-f9cc-11ea-99e0-1830e0c81883.gif)

**Comment by marwie** [comment]
Plugin for osx is currently blocked by not receiving indices in Unity.

**Comment by marwie** [comment]
Fixed bug in osx plugin - will be released in 1.0.4-preview.1

**Comment by marwie** [comment]
1.0.4-preview.1 has been released
